version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg_test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
